project:
  type: website

website:
  title: "simple_quarto_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.ipynb
        text: About Me

format:
  html:
    theme: darkly
    toc: true



